apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloaachen
  #labels:
  #  app: helloaachen
spec:
  selector:
    matchLabels:
      app: helloaachen
 # replicas: 2
  template:
    metadata:
      labels:
        app: helloaachen
    spec:
      containers:
      - name: helloaachen
        image: moaix/helloaachen:v1
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: passwd-volume
          mountPath: /etc/redis-passwd
          readOnly: true
      volumes:
      - name: passwd-volume
        secret:
          secretName: redis-passwd
        
