apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-event-messages
spec:
  template:
    spec:
      containers:
        - name: rabbitmq-client
          image: ghcr.io/kedacore/rabbitmq-client:v1.0
          command:
            [
              "send",
              "amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672",
              "200",
            ]
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 4