# privileged-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
spec:
  containers:
  - name: bad-container
    image: nginx
    securityContext:
      privileged: true
      runAsUser: 0
---

# kube-system-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: kube-system-pod
  namespace: kube-system
spec:
  containers:
  - name: bad-container
    image: nginx
    ports:
    - containerPort: 80

---
# mount-root-fs-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mount-rool-fs-pod
spec:
  containers:
  - name: bad-container
    image: nginx
    volumeMounts:
      - name: host-volume
        mountPath: /host
  volumes:
  - name: host-volume
    hostPath:
      path: /
---
# insecure-context-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: insecure-context-pod
spec:
  containers:
  - name: bad-container
    image: nginx
    securityContext:
      capabilities:
        add: ["SYS_ADMIN", "NET_RAW"]
